export const products2 = [
    {
      id: 11,
      title: "Complete iOS App Development Bootcamp",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS09zoDFsKrJPBVRzn4GDBScZzI0wyHnOBcjwZlmg4aIW3wKOqUhElgQxZVokrqrI9wHN8&usqp=CAU",
      price: "$349",
      rating: 4.9,
    },
    {
      id: 12,
      title: "Android Development with Kotlin",
      image: "https://miro.medium.com/v2/resize:fit:800/0*S9nXLRf9qMv541GB.png",
      price: "$299",
      rating: 4.7,
    },
    {
      id: 13,
      title: "Flutter & Dart - Mobile App Development",
      image: "https://img.freepik.com/free-vector/mobile-app-development-banner_33099-1720.jpg",
      price: "$329",
      rating: 4.8,
    },
    {
      id: 14,
      title: "React Native - Build Mobile Apps",
      image: "https://www.filepicker.io/api/file/4C6yPDywSUeWYLyg1h9G",
      price: "$289",
      rating: 4.6,
    },
    {
      id: 15,
      title: "Swift Programming for iOS",
      image: "https://miro.medium.com/v2/resize:fit:750/1*OgeU8HPo8TFF1cZQ-4XjJw.jpeg",
      price: "$249",
      rating: 4.5,
    },
    {
      id: 16,
      title: "Mobile App UI/UX Design",
      image: "https://miro.medium.com/v2/resize:fit:1165/1*ICPAnKJNLNcskN0Trr9uUA.png",
      price: "$219",
      rating: 4.4,
    },
    {
      id: 17,
      title: "Cross-Platform Mobile App Development",
      image: "https://arateg.com/static/images/blog-native-vs-cross-platform_1920.jpg",
      price: "$319",
      rating: 4.7,
    },
    {
      id: 18,
      title: "Mastering Android Studio",
      image: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210808001314/A-Complete-Guide-to-Learn-Android-Studio-for-Android-App-Development.png",
      price: "$279",
      rating: 4.6,
    },
    {
      id: 19,
      title: "Mobile App Security Essentials",
      image: "https://img-c.udemycdn.com/course/750x422/2783344_520d.jpg",
      price: "$299",
      rating: 4.8,
    },
    {
      id: 20,
      title: "Advanced SwiftUI for iOS",
      image: "https://img-c.udemycdn.com/course/750x422/3680906_291d_5.jpg",
      price: "$339",
      rating: 4.7,
    },
  ];
  