export const products2 = [
    {
      id: 11,
      title: "Complete iOS App Development Bootcamp",
      image: "https://img.freepik.com/free-vector/mobile-app-development-concept-illustration_114360-8383.jpg",
      price: "$349",
      rating: 4.9,
    },
    {
      id: 12,
      title: "Android Development with Kotlin",
      image: "https://img.freepik.com/free-vector/android-operating-system-with-robot_23-2147967035.jpg",
      price: "$299",
      rating: 4.7,
    },
    {
      id: 13,
      title: "Flutter & Dart - Mobile App Development",
      image: "https://img.freepik.com/free-vector/mobile-app-development-banner_33099-1720.jpg",
      price: "$329",
      rating: 4.8,
    },
    {
      id: 14,
      title: "React Native - Build Mobile Apps",
      image: "https://img.freepik.com/free-vector/react-native-mobile-app-development-framework-with-smartphone-vector_53876-158243.jpg",
      price: "$289",
      rating: 4.6,
    },
    {
      id: 15,
      title: "Swift Programming for iOS",
      image: "https://img.freepik.com/free-vector/apple-programming-language-abstract-concept-illustration_335657-3187.jpg",
      price: "$249",
      rating: 4.5,
    },
    {
      id: 16,
      title: "Mobile App UI/UX Design",
      image: "https://img.freepik.com/free-vector/ux-ui-design-with-gradient-screen_23-2148655052.jpg",
      price: "$219",
      rating: 4.4,
    },
    {
      id: 17,
      title: "Cross-Platform Mobile App Development",
      image: "https://img.freepik.com/free-vector/developer-girl-with-code-concept-illustration_114360-6701.jpg",
      price: "$319",
      rating: 4.7,
    },
    {
      id: 18,
      title: "Mastering Android Studio",
      image: "https://img.freepik.com/free-vector/mobile-app-development-concept-illustration_114360-1689.jpg",
      price: "$279",
      rating: 4.6,
    },
    {
      id: 19,
      title: "Mobile App Security Essentials",
      image: "https://img.freepik.com/free-vector/cyber-security-concept-illustration_114360-5349.jpg",
      price: "$299",
      rating: 4.8,
    },
    {
      id: 20,
      title: "Advanced SwiftUI for iOS",
      image: "https://img.freepik.com/free-vector/application-development-concept_1284-63668.jpg",
      price: "$339",
      rating: 4.7,
    },
  ];
  